import type { Game } from "@/types/game";

/**
 * THE GAMES SHELF — companion to `lib/media/music-data.ts`, and under the same
 * contract: original titles and studios only, shaped exactly like the future
 * `GET /games` payload so the swap to a real service is mechanical. Landscape
 * artwork is the locally generated SVG plates under public/store/ — one per
 * game, per-genre palettes, ~2KB each. They used to be picsum URLs, and a
 * picsum outage blanked every plate on the page at once; a storefront whose
 * whole surface is artwork does not get to rent its artwork from a host it
 * does not control.
 *
 * This shelf now feeds the storefront homepage's sections — hero rotation,
 * featured shelf, promo banners, live grid, discover rail — through the
 * selectors in `lib/home/store.ts`. No component reads GAMES directly, so the
 * day a games API ships, that file and this import are the whole swap.
 *
 * GENRES ARE THE CATALOGUE'S OWN WORDS, drawn from the catalogue itself (genre facets are DB-derived since the filter rework)
 * rather than from a games-specific vocabulary ("Roguelike", "Metroidvania"),
 * so a game sits in the same taxonomy as the films and books beside it.
 *
 * ARTWORK COMES IN TWO CROPS OF ONE IMAGE: `artworkUrl` is 16:9 at 800×450
 * for cards and thumbs; `heroArtworkUrl` is the SAME picsum seed at 1600×900
 * so the hero stage and full-bleed banners never upscale — and never show a
 * different picture than the card that advertised them.
 *
 * `descriptionKey` points into home.store.gameCopy: because `mm satisfies
 * typeof en`, a game cannot ship without BOTH languages carrying its copy.
 */
export const GAMES: Game[] = [
  {
    id: "game-lacquer-city",
    title: "Lacquer City",
    studio: "Bagan Interactive",
    artworkUrl: "/store/game-lacquer-city.svg",
    heroArtworkUrl: "/store/game-lacquer-city.svg",
    releaseYear: 2026,
    genre: "Adventure",
    createdAt: "2026-08-19T09:00:00.000Z",
    descriptionKey: "game-lacquer-city",
    platforms: ["PC", "Mobile"],
    priceMMK: 12800,
    rating: 8.6,
    badge: "new",
    playersOnline: 3200,
    eventKey: null,
  },
  {
    id: "game-monsoon-run",
    title: "Monsoon Run",
    studio: "Third Bridge Studio",
    artworkUrl: "/store/game-monsoon-run.svg",
    heroArtworkUrl: "/store/game-monsoon-run.svg",
    releaseYear: 2026,
    genre: "Action",
    createdAt: "2026-07-02T09:00:00.000Z",
    descriptionKey: "game-monsoon-run",
    platforms: ["PC", "Mobile", "Browser"],
    priceMMK: null,
    rating: 8.1,
    badge: "live",
    playersOnline: 12400,
    eventKey: null,
  },
  {
    id: "game-the-long-quiet",
    title: "The Long Quiet",
    studio: "Nightferry",
    artworkUrl: "/store/game-the-long-quiet.svg",
    heroArtworkUrl: "/store/game-the-long-quiet.svg",
    releaseYear: 2025,
    genre: "Horror",
    createdAt: "2025-11-14T09:00:00.000Z",
    descriptionKey: "game-the-long-quiet",
    platforms: ["PC"],
    priceMMK: 15500,
    rating: 9.0,
    badge: "trending",
    playersOnline: 5600,
    eventKey: null,
  },
  {
    id: "game-teahouse-letters",
    title: "Teahouse Letters",
    studio: "Paper Lantern Works",
    artworkUrl: "/store/game-teahouse-letters.svg",
    heroArtworkUrl: "/store/game-teahouse-letters.svg",
    releaseYear: 2025,
    genre: "Drama",
    createdAt: "2025-09-30T09:00:00.000Z",
    descriptionKey: "game-teahouse-letters",
    platforms: ["Mobile", "Browser"],
    priceMMK: 9900,
    rating: 8.8,
    badge: null,
    playersOnline: null,
    eventKey: null,
  },
  {
    id: "game-orbital-ferry",
    title: "Orbital Ferry",
    studio: "Cold Harbour Games",
    artworkUrl: "/store/game-orbital-ferry.svg",
    heroArtworkUrl: "/store/game-orbital-ferry.svg",
    releaseYear: 2025,
    genre: "Sci-Fi",
    createdAt: "2025-06-11T09:00:00.000Z",
    descriptionKey: "game-orbital-ferry",
    platforms: ["PC"],
    priceMMK: 18000,
    rating: 7.9,
    badge: "limited",
    playersOnline: 2100,
    eventKey: "seasonUpdate",
  },
  {
    id: "game-the-ninth-floor",
    title: "The Ninth Floor",
    studio: "Two Rivers Collective",
    artworkUrl: "/store/game-the-ninth-floor.svg",
    heroArtworkUrl: "/store/game-the-ninth-floor.svg",
    releaseYear: 2024,
    genre: "Mystery",
    createdAt: "2024-12-05T09:00:00.000Z",
    descriptionKey: "game-the-ninth-floor",
    platforms: ["PC", "Mobile"],
    priceMMK: 11000,
    rating: 8.3,
    badge: null,
    playersOnline: null,
    eventKey: null,
  },
  {
    id: "game-shwe-market-tycoon",
    title: "Shwe Market",
    studio: "Yangon Playworks",
    artworkUrl: "/store/game-shwe-market-tycoon.svg",
    heroArtworkUrl: "/store/game-shwe-market-tycoon.svg",
    releaseYear: 2024,
    genre: "Family",
    createdAt: "2024-08-22T09:00:00.000Z",
    descriptionKey: "game-shwe-market-tycoon",
    platforms: ["Mobile", "Browser"],
    priceMMK: null,
    rating: 7.6,
    badge: "live",
    playersOnline: 8900,
    eventKey: "multiplayerEvent",
  },
  {
    id: "game-emberfall",
    title: "Emberfall",
    studio: "Sule Forge",
    artworkUrl: "/store/game-emberfall.svg",
    heroArtworkUrl: "/store/game-emberfall.svg",
    releaseYear: 2023,
    genre: "Fantasy",
    createdAt: "2023-10-17T09:00:00.000Z",
    descriptionKey: "game-emberfall",
    platforms: ["PC"],
    priceMMK: 14000,
    rating: 8.9,
    badge: "trending",
    playersOnline: 7400,
    eventKey: null,
  },
  {
    id: "game-delta-drift",
    title: "Delta Drift",
    studio: "Ayeyarwady Softworks",
    artworkUrl: "/store/game-delta-drift.svg",
    heroArtworkUrl: "/store/game-delta-drift.svg",
    releaseYear: 2026,
    genre: "Crime",
    createdAt: "2026-05-08T09:00:00.000Z",
    descriptionKey: "game-delta-drift",
    platforms: ["PC", "Mobile"],
    priceMMK: null,
    rating: 7.8,
    badge: "live",
    playersOnline: 15600,
    eventKey: "multiplayerEvent",
  },
  {
    id: "game-paper-tigers",
    title: "Paper Tigers",
    studio: "Hinthar Play",
    artworkUrl: "/store/game-paper-tigers.svg",
    heroArtworkUrl: "/store/game-paper-tigers.svg",
    releaseYear: 2025,
    genre: "History",
    createdAt: "2025-03-21T09:00:00.000Z",
    descriptionKey: "game-paper-tigers",
    platforms: ["PC", "Browser"],
    priceMMK: 13500,
    rating: 8.4,
    badge: null,
    playersOnline: null,
    eventKey: null,
  },
  {
    id: "game-starlit-bazaar",
    title: "Starlit Bazaar",
    studio: "Moe Kaung Studio",
    artworkUrl: "/store/game-starlit-bazaar.svg",
    heroArtworkUrl: "/store/game-starlit-bazaar.svg",
    releaseYear: 2027,
    genre: "Romance",
    createdAt: "2026-08-28T09:00:00.000Z",
    descriptionKey: "game-starlit-bazaar",
    platforms: ["PC", "Mobile"],
    priceMMK: null,
    rating: null,
    badge: "comingSoon",
    playersOnline: null,
    eventKey: null,
  },
  {
    id: "game-signal-thirty",
    title: "Signal Thirty",
    studio: "Mandalay Arcade",
    artworkUrl: "/store/game-signal-thirty.svg",
    heroArtworkUrl: "/store/game-signal-thirty.svg",
    releaseYear: 2026,
    genre: "Thriller",
    createdAt: "2026-06-14T09:00:00.000Z",
    descriptionKey: "game-signal-thirty",
    platforms: ["Browser"],
    priceMMK: 8800,
    rating: 8.0,
    badge: null,
    playersOnline: null,
    eventKey: null,
  },
];
